services:
    Indykoning\GrumPHPDuster\DusterTask:
        class: \Indykoning\GrumPHPDuster\DusterTask
        arguments:
            - "@process_builder"
            - "@formatter.raw_process"
        tags:
            - { name: grumphp.task, task: duster }
